// Mock data fallback when DATABASE_URL not configured. Also used for fixtures/tests.
export type MockProperty = {
  id: string;
  externalId: string;
  servicer: string;
  title: string;
  description: string;
  price: number; // euros
  propertyType: string;
  status: string;
  addressRaw: string;
  addressNormalized: string;
  province: string;
  municipality: string;
  postalCode: string;
  latitude: number;
  longitude: number;
  geocodeConfidence: "high" | "medium" | "low";
  approximateLocation: boolean;
  areaM2: number | null;
  rooms: number | null;
  bathrooms: number | null;
  yearBuilt: number | null;
  energyCert: string | null;
  photos: string[];
  sourceUrl: string;
  lastSeenAt: string;
  createdAt: string;
};

export const SERVICERS = [
  { id: "aliseda", displayName: "Aliseda (Santander)", enabled: true },
  { id: "servihabitat", displayName: "Servihabitat (CaixaBank)", enabled: true },
  { id: "haya", displayName: "Haya Real Estate", enabled: true },
  { id: "altamira", displayName: "Altamira / doValue", enabled: true },
  { id: "solvia", displayName: "Solvia (Sabadell)", enabled: true },
  { id: "anticipa", displayName: "Anticipa Real Estate", enabled: true },
  { id: "diglo", displayName: "Diglo (Ibercaja)", enabled: true },
  { id: "hipoges", displayName: "Hipoges", enabled: true },
];

export const MOCK_PROPERTIES: MockProperty[] = [
  {
    id: "1",
    externalId: "ALI-001",
    servicer: "aliseda",
    title: "Piso 3 habitaciones en Vallecas",
    description: "Piso luminoso de 85 m² con salón amplio, cocina equipada y terraza. Ideal inversión.",
    price: 98500,
    propertyType: "piso",
    status: "disponible",
    addressRaw: "Calle Real 12, Vallecas, Madrid",
    addressNormalized: "Calle Real 12, 28031 Madrid",
    province: "Madrid",
    municipality: "Madrid",
    postalCode: "28031",
    latitude: 40.376,
    longitude: -3.62,
    geocodeConfidence: "high",
    approximateLocation: false,
    areaM2: 85,
    rooms: 3,
    bathrooms: 1,
    yearBuilt: 1975,
    energyCert: "E",
    photos: ["https://picsum.photos/seed/wh1/800/600", "https://picsum.photos/seed/wh1b/800/600"],
    sourceUrl: "https://www.alisedainmobiliaria.com/detalle/ALI-001",
    lastSeenAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 10).toISOString(),
  },
  {
    id: "2",
    externalId: "SHB-204",
    servicer: "servihabitat",
    title: "Ático con terraza en Eixample",
    description: "Ático 110 m² con terraza 30 m², 4 hab, reforma a estrenar.",
    price: 189000,
    propertyType: "atico",
    status: "disponible",
    addressRaw: "Carrer de Mallorca 400, Barcelona",
    addressNormalized: "Carrer de Mallorca 400, 08013 Barcelona",
    province: "Barcelona",
    municipality: "Barcelona",
    postalCode: "08013",
    latitude: 41.405,
    longitude: 2.177,
    geocodeConfidence: "high",
    approximateLocation: false,
    areaM2: 110,
    rooms: 4,
    bathrooms: 2,
    yearBuilt: 1968,
    energyCert: "D",
    photos: ["https://picsum.photos/seed/wh2/800/600"],
    sourceUrl: "https://www.servihabitat.com/es/detalle/SHB-204",
    lastSeenAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
  },
  {
    id: "3",
    externalId: "HAYA-3321",
    servicer: "haya",
    title: "Casa con parcela en Paterna",
    description: "Casa independiente 140 m² + parcela 400 m², 3 habitaciones, piscina.",
    price: 135000,
    propertyType: "casa",
    status: "disponible",
    addressRaw: "Camí de la Canyada 45, Paterna, Valencia",
    addressNormalized: "Camí de la Canyada 45, 46980 Paterna",
    province: "Valencia",
    municipality: "Paterna",
    postalCode: "46980",
    latitude: 39.502,
    longitude: -0.44,
    geocodeConfidence: "medium",
    approximateLocation: false,
    areaM2: 140,
    rooms: 3,
    bathrooms: 2,
    yearBuilt: 1995,
    energyCert: "C",
    photos: ["https://picsum.photos/seed/wh3/800/600", "https://picsum.photos/seed/wh3b/800/600", "https://picsum.photos/seed/wh3c/800/600"],
    sourceUrl: "https://www.haya.es/inmueble/HAYA-3321",
    lastSeenAt: new Date().toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7).toISOString(),
  },
  {
    id: "4",
    externalId: "ALT-778",
    servicer: "altamira",
    title: "Local comercial en Triana - Sevilla",
    description: "Local 90 m² a pie de calle, escaparate, ideal negocio.",
    price: 72000,
    propertyType: "local",
    status: "disponible",
    addressRaw: "Calle Pureza 88, Sevilla",
    addressNormalized: "Calle Pureza 88, 41010 Sevilla",
    province: "Sevilla",
    municipality: "Sevilla",
    postalCode: "41010",
    latitude: 37.384,
    longitude: -6.007,
    geocodeConfidence: "high",
    approximateLocation: false,
    areaM2: 90,
    rooms: null,
    bathrooms: 1,
    yearBuilt: 1980,
    energyCert: null,
    photos: ["https://picsum.photos/seed/wh4/800/600"],
    sourceUrl: "https://www.altamirainmuebles.com/ALT-778",
    lastSeenAt: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 15).toISOString(),
  },
  {
    id: "5",
    externalId: "SOL-901",
    servicer: "solvia",
    title: "Suelo urbano en Zaragoza - 800 m²",
    description: "Parcela urbana consolidada, edificable, servicios en puerta.",
    price: 55000,
    propertyType: "suelo_urbano",
    status: "disponible",
    addressRaw: "Calle de la Isuela, Zaragoza",
    addressNormalized: "Calle de la Isuela, 50012 Zaragoza",
    province: "Zaragoza",
    municipality: "Zaragoza",
    postalCode: "50012",
    latitude: 41.62,
    longitude: -0.91,
    geocodeConfidence: "low",
    approximateLocation: true,
    areaM2: 800,
    rooms: null,
    bathrooms: null,
    yearBuilt: null,
    energyCert: null,
    photos: [],
    sourceUrl: "https://www.solvia.es/SOL-901",
    lastSeenAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 20).toISOString(),
  },
  {
    id: "6",
    externalId: "ANT-445",
    servicer: "anticipa",
    title: "Piso 2 hab en Malasaña",
    description: "Piso 65 m² para reformar, balcón, muy luminoso.",
    price: 145000,
    propertyType: "piso",
    status: "reservado",
    addressRaw: "Calle San Vicente Ferrer 20, Madrid",
    addressNormalized: "Calle San Vicente Ferrer 20, 28004 Madrid",
    province: "Madrid",
    municipality: "Madrid",
    postalCode: "28004",
    latitude: 40.426,
    longitude: -3.704,
    geocodeConfidence: "high",
    approximateLocation: false,
    areaM2: 65,
    rooms: 2,
    bathrooms: 1,
    yearBuilt: 1960,
    energyCert: "F",
    photos: ["https://picsum.photos/seed/wh6/800/600"],
    sourceUrl: "https://www.anticipa.com/ANT-445",
    lastSeenAt: new Date(Date.now() - 1000 * 60 * 60 * 1).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
  },
  {
    id: "7",
    externalId: "DIG-12",
    servicer: "diglo",
    title: "Garaje en Ruzafa",
    description: "Plaza de garaje 12 m², acceso automático.",
    price: 12000,
    propertyType: "garaje",
    status: "disponible",
    addressRaw: "Calle Cádiz 40, Valencia",
    addressNormalized: "Calle Cádiz 40, 46006 Valencia",
    province: "Valencia",
    municipality: "Valencia",
    postalCode: "46006",
    latitude: 39.461,
    longitude: -0.377,
    geocodeConfidence: "high",
    approximateLocation: false,
    areaM2: 12,
    rooms: null,
    bathrooms: null,
    yearBuilt: null,
    energyCert: null,
    photos: ["https://picsum.photos/seed/wh7/800/600"],
    sourceUrl: "https://www.diglo.es/DIG-12",
    lastSeenAt: new Date().toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
  },
  {
    id: "8",
    externalId: "HAYA-9001",
    servicer: "haya",
    title: "Chalet adosado en Dos Hermanas",
    description: "Chalet 160 m², 4 hab, jardín, urbanización privada.",
    price: 165000,
    propertyType: "chalet",
    status: "disponible",
    addressRaw: "Calle Arenal, Dos Hermanas, Sevilla",
    addressNormalized: "Calle Arenal, 41702 Dos Hermanas",
    province: "Sevilla",
    municipality: "Dos Hermanas",
    postalCode: "41702",
    latitude: 37.28,
    longitude: -5.92,
    geocodeConfidence: "medium",
    approximateLocation: false,
    areaM2: 160,
    rooms: 4,
    bathrooms: 3,
    yearBuilt: 2005,
    energyCert: "B",
    photos: ["https://picsum.photos/seed/wh8/800/600"],
    sourceUrl: "https://www.haya.es/HAYA-9001",
    lastSeenAt: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 12).toISOString(),
  },
  {
    id: "9",
    externalId: "ALI-889",
    servicer: "aliseda",
    title: "Estudio en Benidorm",
    description: "Estudio 35 m² a 200m playa, vistas mar.",
    price: 48000,
    propertyType: "estudio",
    status: "disponible",
    addressRaw: "Avenida Mediterráneo, Benidorm, Alicante",
    addressNormalized: "Avenida Mediterráneo, 03501 Benidorm",
    province: "Alicante",
    municipality: "Benidorm",
    postalCode: "03501",
    latitude: 38.535,
    longitude: -0.131,
    geocodeConfidence: "low",
    approximateLocation: true,
    areaM2: 35,
    rooms: 1,
    bathrooms: 1,
    yearBuilt: 1990,
    energyCert: "E",
    photos: ["https://picsum.photos/seed/wh9/800/600"],
    sourceUrl: "https://www.alisedainmobiliaria.com/ALI-889",
    lastSeenAt: new Date(Date.now() - 1000 * 60 * 60 * 20).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 30).toISOString(),
  },
  {
    id: "10",
    externalId: "SHB-501",
    servicer: "servihabitat",
    title: "Nave industrial en Polígono Malpica - Zaragoza",
    description: "Nave 500 m² con oficinas y muelle de carga.",
    price: 210000,
    propertyType: "nave",
    status: "disponible",
    addressRaw: "Polígono Malpica, Zaragoza",
    addressNormalized: "Polígono Malpica, 50016 Zaragoza",
    province: "Zaragoza",
    municipality: "Zaragoza",
    postalCode: "50016",
    latitude: 41.66,
    longitude: -0.85,
    geocodeConfidence: "medium",
    approximateLocation: true,
    areaM2: 500,
    rooms: null,
    bathrooms: 2,
    yearBuilt: 2000,
    energyCert: null,
    photos: ["https://picsum.photos/seed/wh10/800/600"],
    sourceUrl: "https://www.servihabitat.com/SHB-501",
    lastSeenAt: new Date().toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 8).toISOString(),
  },
  // + 6 más para clustering demo
  {
    id: "11",
    externalId: "ALI-102",
    servicer: "aliseda",
    title: "Piso 4 hab en Latina",
    description: "Piso familiar 95 m² con ascensor.",
    price: 110000,
    propertyType: "piso",
    status: "disponible",
    addressRaw: "Calle Guabairo, Madrid",
    addressNormalized: "Calle Guabairo, 28024 Madrid",
    province: "Madrid",
    municipality: "Madrid",
    postalCode: "28024",
    latitude: 40.405,
    longitude: -3.76,
    geocodeConfidence: "high",
    approximateLocation: false,
    areaM2: 95,
    rooms: 4,
    bathrooms: 2,
    yearBuilt: 1982,
    energyCert: "E",
    photos: ["https://picsum.photos/seed/wh11/800/600"],
    sourceUrl: "https://www.alisedainmobiliaria.com/ALI-102",
    lastSeenAt: new Date().toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 4).toISOString(),
  },
  {
    id: "12",
    externalId: "SHB-812",
    servicer: "servihabitat",
    title: "Ático en Gràcia",
    description: "Ático 75 m² con terraza 15 m².",
    price: 245000,
    propertyType: "atico",
    status: "disponible",
    addressRaw: "Carrer de Verdi, Barcelona",
    addressNormalized: "Carrer de Verdi, 08012 Barcelona",
    province: "Barcelona",
    municipality: "Barcelona",
    postalCode: "08012",
    latitude: 41.403,
    longitude: 2.157,
    geocodeConfidence: "high",
    approximateLocation: false,
    areaM2: 75,
    rooms: 2,
    bathrooms: 1,
    yearBuilt: 1970,
    energyCert: "E",
    photos: ["https://picsum.photos/seed/wh12/800/600"],
    sourceUrl: "https://www.servihabitat.com/SHB-812",
    lastSeenAt: new Date().toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 6).toISOString(),
  },
  {
    id: "13",
    externalId: "HAYA-2100",
    servicer: "haya",
    title: "Piso en Cabanyal",
    description: "Piso 70 m² a reformar, cerca playa Malvarrosa.",
    price: 89000,
    propertyType: "piso",
    status: "disponible",
    addressRaw: "Calle Mediterráneo, Valencia",
    addressNormalized: "Calle Mediterráneo, 46011 Valencia",
    province: "Valencia",
    municipality: "Valencia",
    postalCode: "46011",
    latitude: 39.476,
    longitude: -0.325,
    geocodeConfidence: "high",
    approximateLocation: false,
    areaM2: 70,
    rooms: 3,
    bathrooms: 1,
    yearBuilt: 1965,
    energyCert: "F",
    photos: ["https://picsum.photos/seed/wh13/800/600"],
    sourceUrl: "https://www.haya.es/HAYA-2100",
    lastSeenAt: new Date().toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 9).toISOString(),
  },
  {
    id: "14",
    externalId: "SOL-312",
    servicer: "solvia",
    title: "Casa rural en Teruel",
    description: "Casa 120 m² + corral, para rehabilitar.",
    price: 32000,
    propertyType: "casa",
    status: "disponible",
    addressRaw: "Calle Mayor, Mora de Rubielos, Teruel",
    addressNormalized: "Calle Mayor, 44400 Mora de Rubielos",
    province: "Teruel",
    municipality: "Mora de Rubielos",
    postalCode: "44400",
    latitude: 40.25,
    longitude: -0.75,
    geocodeConfidence: "medium",
    approximateLocation: false,
    areaM2: 120,
    rooms: 3,
    bathrooms: 1,
    yearBuilt: 1950,
    energyCert: null,
    photos: ["https://picsum.photos/seed/wh14/800/600"],
    sourceUrl: "https://www.solvia.es/SOL-312",
    lastSeenAt: new Date().toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 11).toISOString(),
  },
  {
    id: "15",
    externalId: "ALT-990",
    servicer: "altamira",
    title: "Edificio residencial en Valladolid",
    description: "Edificio 6 viviendas, 800 m² construidos.",
    price: 420000,
    propertyType: "edificio",
    status: "disponible",
    addressRaw: "Calle Santiago, Valladolid",
    addressNormalized: "Calle Santiago, 47001 Valladolid",
    province: "Valladolid",
    municipality: "Valladolid",
    postalCode: "47001",
    latitude: 41.652,
    longitude: -4.728,
    geocodeConfidence: "high",
    approximateLocation: false,
    areaM2: 800,
    rooms: 12,
    bathrooms: 6,
    yearBuilt: 1978,
    energyCert: null,
    photos: ["https://picsum.photos/seed/wh15/800/600"],
    sourceUrl: "https://www.altamirainmuebles.com/ALT-990",
    lastSeenAt: new Date().toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 13).toISOString(),
  },
  {
    id: "16",
    externalId: "HIPO-001",
    servicer: "hipoges",
    title: "Piso en Bilbao - Deusto",
    description: "Piso 80 m², 3 hab, vistas a la ría.",
    price: 125000,
    propertyType: "piso",
    status: "disponible",
    addressRaw: "Lehendakari Aguirre, Bilbao",
    addressNormalized: "Lehendakari Aguirre, 48014 Bilbao",
    province: "Bizkaia",
    municipality: "Bilbao",
    postalCode: "48014",
    latitude: 43.267,
    longitude: -2.95,
    geocodeConfidence: "high",
    approximateLocation: false,
    areaM2: 80,
    rooms: 3,
    bathrooms: 1,
    yearBuilt: 1972,
    energyCert: "E",
    photos: ["https://picsum.photos/seed/wh16/800/600"],
    sourceUrl: "https://www.hipoges.com/HIPO-001",
    lastSeenAt: new Date().toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
  },
];
